// Stripe product and price IDs for Streamwalkers Trader Pro
// All products created in Stripe — do not use price_data

export const CHALLENGE_TIERS = {
  "25k": {
    product_id: "prod_U9KfbuelyJNYUj",
    price_id: "price_1TB20MDHerWbKqqdyAZi5XB1",
    name: "$25K Challenge",
    accountSize: "$25,000",
    fee: "$79",
    feeAmount: 79,
    profitTarget: "$1,500",
    maxDrawdown: "$1,000",
    features: [
      "All Trading Tools Included",
      "Basic Order Flow Suite",
      "Daily Loss Limit: $500",
      "Profit Target: $1,500",
      "Email Support",
      "Educational Videos",
    ],
  },
  "50k": {
    product_id: "prod_U9KfG0OeMBK8yH",
    price_id: "price_1TB20TDHerWbKqqda6S4ej4V",
    name: "$50K Challenge",
    accountSize: "$50,000",
    fee: "$139",
    feeAmount: 139,
    profitTarget: "$3,000",
    maxDrawdown: "$2,000",
    features: [
      "All Trading Tools Included",
      "Advanced Indicators Suite",
      "Daily Loss Limit: $1,000",
      "Profit Target: $3,000",
      "Priority Support",
      "Live Trading Sessions",
    ],
  },
  "100k": {
    product_id: "prod_U9KfbdIblixip0",
    price_id: "price_1TB20aDHerWbKqqdXNO1jZnV",
    name: "$100K Challenge",
    accountSize: "$100,000",
    fee: "$249",
    feeAmount: 249,
    profitTarget: "$6,000",
    maxDrawdown: "$3,000",
    popular: true,
    features: [
      "All Trading Tools Included",
      "Advanced Indicators Suite",
      "Trade Copier Access",
      "Daily Loss Limit: $2,000",
      "Profit Target: $6,000",
      "Priority Support",
      "AI Trade Analysis",
      "Risk Management Tools",
    ],
  },
  "200k": {
    product_id: "prod_U9KfOSpv75ZrNC",
    price_id: "price_1TB20bDHerWbKqqdIlhrZYwX",
    name: "$200K Challenge",
    accountSize: "$200,000",
    fee: "$399",
    feeAmount: 399,
    profitTarget: "$12,000",
    maxDrawdown: "$6,000",
    features: [
      "All Trading Tools Included",
      "Custom Automation Tools",
      "1-on-1 Mentorship",
      "Daily Loss Limit: $4,000",
      "Profit Target: $12,000",
      "White-Glove Support",
      "AI Coaching & Analytics",
      "Exclusive Community Access",
      "API Access",
    ],
  },
} as const;

export const INSTANT_FUNDING = {
  "10k": {
    product_id: "prod_U9KfT2So3KhELD",
    price_id: "price_1TB20dDHerWbKqqdZuLhdreo",
    name: "$10K Instant Funding",
    accountSize: "$10,000",
    fee: "$299",
    feeAmount: 299,
  },
  "25k": {
    product_id: "prod_U9KgvQD9mqbmH0",
    price_id: "price_1TB20eDHerWbKqqdW60D6aa0",
    name: "$25K Instant Funding",
    accountSize: "$25,000",
    fee: "$499",
    feeAmount: 499,
  },
  "50k": {
    product_id: "prod_U9KgzGywhuKWYA",
    price_id: "price_1TB20fDHerWbKqqdxLX7UBW5",
    name: "$50K Instant Funding",
    accountSize: "$50,000",
    fee: "$899",
    feeAmount: 899,
  },
} as const;

export const AI_MEMBERSHIP = {
  product_id: "prod_U9Kg0uvAfrojW3",
  price_id: "price_1TB20hDHerWbKqqdjW5dIzks",
  name: "TraderPro AI Membership",
  fee: "$39/month",
  feeAmount: 39,
  features: [
    "AI Trade Analysis",
    "Strategy Library",
    "Market Intelligence",
    "Trader Analytics Dashboard",
    "AI Coaching Suggestions",
    "Trader Score & Rankings",
  ],
} as const;
