import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { InfoTooltip } from "@/components/InfoTooltip";
import { Download, FileText, Calendar, BarChart3 } from "lucide-react";

const Reports = () => {
  const reports = [
    {
      id: 1,
      name: "Monthly P&L Report",
      description: "Detailed profit and loss analysis for the current month",
      type: "P&L",
      date: "2024-01-31",
      status: "Ready",
      size: "2.3 MB"
    },
    {
      id: 2,
      name: "Risk Assessment Report",
      description: "Comprehensive risk analysis and recommendations",
      type: "Risk",
      date: "2024-01-30",
      status: "Ready",
      size: "1.8 MB"
    },
    {
      id: 3,
      name: "Trading Activity Summary",
      description: "Complete trading history and statistics",
      type: "Activity",
      date: "2024-01-29",
      status: "Processing",
      size: "4.1 MB"
    },
    {
      id: 4,
      name: "Tax Report 2024",
      description: "Annual tax documentation for trading activities",
      type: "Tax",
      date: "2024-01-28",
      status: "Ready",
      size: "876 KB"
    }
  ];

  return (
    <div className="container mx-auto p-6 space-y-8">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Trading Reports</h1>
          <p className="text-muted-foreground">
            Generate and download detailed reports of your trading activity.
          </p>
        </div>
        <Button>
          <FileText className="mr-2 h-4 w-4" />
          Generate New Report
        </Button>
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <div className="flex items-center gap-1">
              <CardTitle className="text-sm font-medium">Total Reports</CardTitle>
              <InfoTooltip content="The total number of reports generated for your trading account, including all types of analysis and documentation." />
            </div>
            <FileText className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">24</div>
            <p className="text-xs text-muted-foreground">
              +3 from last month
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <div className="flex items-center gap-1">
              <CardTitle className="text-sm font-medium">Ready for Download</CardTitle>
              <InfoTooltip content="Reports that have been fully processed and are available for immediate download in PDF or Excel format." />
            </div>
            <Download className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">18</div>
            <p className="text-xs text-muted-foreground">
              Available now
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <div className="flex items-center gap-1">
              <CardTitle className="text-sm font-medium">Processing</CardTitle>
              <InfoTooltip content="Reports currently being generated by our system. Processing time depends on the complexity and date range of the report." />
            </div>
            <BarChart3 className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">3</div>
            <p className="text-xs text-muted-foreground">
              ETA: 15 minutes
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <div className="flex items-center gap-1">
              <CardTitle className="text-sm font-medium">This Month</CardTitle>
              <InfoTooltip content="Number of reports generated in the current month, helping you track your reporting activity and compliance needs." />
            </div>
            <Calendar className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">7</div>
            <p className="text-xs text-muted-foreground">
              Reports generated
            </p>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Recent Reports</CardTitle>
          <CardDescription>Your latest generated trading reports</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {reports.map((report) => (
              <div key={report.id} className="flex items-center justify-between p-4 border rounded-lg">
                <div className="space-y-1">
                  <div className="flex items-center gap-2">
                    <h3 className="font-medium">{report.name}</h3>
                    <Badge variant={report.status === "Ready" ? "default" : "secondary"}>
                      {report.status}
                    </Badge>
                  </div>
                  <p className="text-sm text-muted-foreground">{report.description}</p>
                  <div className="flex items-center gap-4 text-xs text-muted-foreground">
                    <div className="flex items-center gap-1">
                      <span>Type: {report.type}</span>
                      <InfoTooltip content={
                        report.type === "P&L" ? "Profit and Loss report showing your trading performance and financial results." :
                        report.type === "Risk" ? "Risk analysis report detailing your risk exposure and management effectiveness." :
                        report.type === "Activity" ? "Complete trading history including all transactions, orders, and market activity." :
                        "Tax documentation report for compliance and filing purposes with relevant authorities."
                      } />
                    </div>
                    <span>Date: {report.date}</span>
                    <span>Size: {report.size}</span>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  {report.status === "Ready" && (
                    <Button variant="outline" size="sm">
                      <Download className="mr-2 h-4 w-4" />
                      Download
                    </Button>
                  )}
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default Reports;