// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfcnxybvwcxfuksnqngq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmY254eWJ2d2N4ZnVrc25xbmdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3Mzc0MTcsImV4cCI6MjA2MzMxMzQxN30.NCpKnawX8_TBY7mbRX4dPznCTBGNaiSmIixNR4_j6FY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});